REFDIR: ~/SIMBA/
SCRIPTSDIR: ~/SIMBA/pyScripts/
READSDIR: ~/SIMBA/raw_reads
mainEnv_yaml: ~/SIMBA/mainEnv.yaml
ntDatabaseDir: ~/SIMBA/databases/ntDatabaseDir/nt
nucVirTotal: ~/SIMBA/databases/viral_refseq_nuc/viralRefseqNuc
micoDB: ~/SIMBA/databases/microbeDB/micoDB
bactRefseqSlim_nuc: ~/SIMBA/databases/bacterialRefseq_slim_nuc/bacterialRefseq_slim_nuc
fungalRefseqSlim_nuc: ~/SIMBA/databases/fungalRefseqSlim_nuc/bacterialRefseq_slim_nuc
gtf: ~/SIMBA/databases/human_release34/hg38.ERCC.gtf
stardir: ~/SIMBA/databases/human_release34/starIndexWithERCC/
cname: ~/SIMBA/databases/human_release34/chrName.txt


