#important directories
dir: /oak/stanford/groups/quake/gita/raw/tab1_20200407/secondAnalysis
aligned_dir: /oak/stanford/groups/quake/gita/raw/covid2_20200523/alignedToVecs
inputSeqs: /oak/stanford/groups/quake/gita/raw/covid2_20200523/dereplicated
fastaSplit: /oak/stanford/groups/quake/gita/raw/covid2_20200523/fastaSplit/

#script locations in $GROUP_HOME/gita
nrBlast_script: /home/groups/quake/gita/scripts/nrBlast.py
fasta_split: /home/groups/quake/gita/scripts/fastaSplit.py
summary: /home/groups/quake/gita/scripts/dataSummary.py 
csv: /home/groups/quake/gita/scripts/convertToCsv.py

#yaml locations in $OAK/gita
fastqc_yaml: /oak/stanford/groups/quake/gita/raw/env/fastqc.yaml
bowtie2_yaml: /oak/stanford/groups/quake/gita/raw/env/bowtie2.yaml
samtools_yaml: /oak/stanford/groups/quake/gita/raw/env/samtools.yaml
nrBlast_yaml: /oak/stanford/groups/quake/gita/raw/env/nrBlast.yaml
usearch_yaml: /oak/stanford/groups/quake/gita/raw/env/usearch.yaml
vsearch_yaml: /oak/stanford/groups/quake/gita/raw/env/vsearch.yaml
biop_yaml: /oak/stanford/groups/quake/gita/raw/env/biop.yaml #biopython1.74
meta_yaml: /oak/stanford/groups/quake/gita/raw/env/meta.yaml
metaAux_yaml: /oak/stanford/groups/quake/gita/raw/env/metaAux.yaml
python3_yaml: /oak/stanford/groups/quake/gita/raw/env/python3.yaml
pySkPd_yaml: /oak/stanford/groups/quake/gita/raw/env/pySkPd.yaml
rtk_yaml: /oak/stanford/groups/quake/gita/raw/env/rtk.yaml
qiime2_yaml: /oak/stanford/groups/quake/gita/raw/env/qiime2.yaml
star_yaml: /oak/stanford/groups/quake/gita/raw/env/star.yaml
mainEnv_yaml: /oak/stanford/groups/quake/gita/raw/env/mainEnv.yaml
mainEnv2_yaml: /oak/stanford/groups/quake/gita/raw/env/mainEnv2.yaml
simba_yaml: /oak/stanford/groups/quake/gita/raw/env/simba_env2.yaml

#rule fastqc
name_fastqc: fastqc
mem_fastqc: 16000
threads_fastqc: 4

#rule trimmomatic
version_trim: 0.39
name_trim: trimmomatic
mem_trim: 16000
threads_trim: 4
trim_software_dir: /home/groups/quake/gita/software/Trimmomatic-0.39/trimmomatic-0.39.jar
trim_adaptor_dir: /home/groups/quake/gita/software/Trimmomatic-0.39/adapters/NexteraPE-PE.fa
leading: 3
trailing: 3
minlen: 36

#rule 
version_merge: 1.2.11
name_merge: merge_paired_reads
mem_merge: 16000
threads_merge: 4
flash_dir: /home/groups/quake/gita/software/FLASH-1.2.11/flash
max_len: 400

#rule align_to_contamination_vectors
name_align_to_cont_vec: align_to_contamination_vectors
mem_bowtie: 16000
threads_bowtie: 4
database_dir: /oak/stanford/groups/quake/gita/raw/database/univec/univec

#rule filter_contaminating_vectors
name_filter: filter_contamination
mem_filter: 16000
threads_filter: 4

#rule align_to_human_genome
name_human: align_to_human_genome
mem_human: 32000
threads_human: 8
human_database_dir: /oak/stanford/groups/quake/gita/raw/database/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index

#rule filter_human_reads
name_human_filtered: filter_human_genome
mem_human_filtered: 16000
threads_human_filtered: 4

#rule dereplicate
name_dereplicate: dereplicate
mem_dereplicate: 16000
threads_dereplicate: 4

#rule OTUs
#name_OTUs: otus_perSample
#percent_id_threshold: 0.98

#rule fasta_split
name_split: fasta_split
mem_split: 16000
threads_split: 4
batch_size: 500 #no. of fasta records to write per file

#rule blast_toNR
name_blast_toNR: blast_toNR
mem_blast_toNR: 80000
threads_blast_toNR: 18
eval_max: 1e-5

#rule virBlastn or virBlastx
mem_virBlastn: 16000
mem_virBlastx: 32000
threads_virBlastn: 4
threads_virBlastx: 8

#standard kraken database (plus fungi and protozoa)
standard: /oak/stanford/groups/quake/gita/raw/database/krakdbs/standard

#nt kraken database
nt: /oak/stanford/groups/quake/gita/raw/database/krakdbs/nt

nrDatabaseDir: /oak/stanford/groups/quake/lsidow/blastdb/nr/nr

bactRefDb: /oak/stanford/groups/quake/gita/raw/database/bactRefDb_june10_2020/ref_prok_rep_genomes
mem_blast_toBactRefDb: 64000
threads_blast_toBactRefDb: 16

#nrDatabaseDir: /oak/stanford/groups/quake/gita/raw/database/nr/nr
#blast output qseqid (query id) sseqid (subject id) pident (percentage of identical matches) length (alignment length) mismatch (num mismatch) gapopen (number of gap openings) qstart (start of alignment in query)
#qend (end of alignment in query) sstart (start of alignment in subject) send (end of alignment in subject) evalue bitscore

#ntDatabaseDir contains nucleotide sequences (all from NCBI) downloaded in Nov 2020
ntDatabaseDir: /oak/stanford/groups/quake/gita/raw/database/nt_Nov02_2020/nt

#ntDatabaseDir2 contains nucleotide sequences (all from NCBI) downloaded in Aug 2021 (NOTE I redownloaded this db because the previous one seemed corrupt but it wasn't) 
ntDatabaseDir2: /oak/stanford/groups/quake/gita/raw/database/nt_Aug12_2021/nt

#pathogenDB (With ~10 intracellular bacterial pathogens)
nucVirSubset: /oak/stanford/groups/quake/gita/raw/database/nucVirSubset/pathogenDb

#the virus-only version of pathogenDB from above
nucVirSubsetv2_virusOnlyNoBact: /oak/stanford/groups/quake/gita/raw/database/nucVirSubsetv2_virusOnlyNoBact/virPathogenDB

# protVirSubset is the protein version of nucVirSubset (pathogenDB), so it does contain bact. intracellular pathogens like TB
protVirSubset: /oak/stanford/groups/quake/gita/raw/database/protVirSubset/pathogenProts

#the virus refseq database (all viruses) nucleotide version
nucVirTotal: /oak/stanford/groups/quake/gita/raw/database/viral_nr_march25_2020/viral_refseq_nuc/viralRefseqNuc

#the virus refseq database (all viruses) protein version 
protVirTotal: /oak/stanford/groups/quake/gita/raw/database/protVirTotalNR/viralProtDatabase

#this is the database that contains the intersection of the HumGut database and refseq bacterial database, in addition to ~10 intracellular bact. pathogens
microbeDB: /oak/stanford/groups/quake/gita/raw/database/microbeDB_jan2021_bact/microbeDB

#this is the database that is the much reduced version of NCBI's fungal refseq database, containing only representative genomes, and up to 5 species per genus, among certain genera mostly found #in the human body
mycoDB_5sp: /oak/stanford/groups/quake/gita/raw/database/fungalDB/mycoDB_5spPerGen_Jan2021/mycoDB_5spPerGen  

#this is the combination of the top two databases (microbeDB and mycoDB_5sp)
micoDB: /oak/stanford/groups/quake/gita/raw/database/micoDB_Feb2021_bactANDfungal/micoDB

#bacterial refseq (slim) (nucleotide with nuc extention, and protein with prot extension) it contains only one randomly selected strain per species (>4000 genomes)
bactRefseqSlim_nuc: /oak/stanford/groups/quake/gita/raw/database/bactRepSeqs_Dec2020/bacterialRefseq_unique_jan2021/bacterialRefseq_slim_nuc
bactRefseqSlim_prot: /oak/stanford/groups/quake/gita/raw/database/bactRepSeqs_Dec2020/bacterialRefseq_unique_jan2021/bacterialRefseq_slim_prot

#fungal refseq (slim) nucl and prot, contains only one representative strain per species (~2600 species, as opposed to the original 7500+)- obtained Jan 2021
fungalRefseqSlim_nuc: /oak/stanford/groups/quake/gita/raw/database/fungalDB/mycoDB/fungalRefseqSlim_nuc
fungalRefseqSlim_prot: /oak/stanford/groups/quake/gita/raw/database/fungalDB/mycoDB/fungalRefseqSlim_prot

#human genome along with synthetic chromosome constructs
human_genome: /oak/stanford/groups/quake/gita/raw/database/human_genome_and_synthetic_chromosomes_july2021/humanGenomeAndSyntheticConstDB


#rule dedup
mem_dedup: 16000
threads_dedup: 4

#rule metaphlan
name_meta: meta
mem_meta: 16000
threads_meta: 4
#metaBowtie_dir is no longer going to work. Need to figure out where the metaphlan_databases is located, since the env in the users/gitam/...was deleted.
metaBowtie_dir: /home/users/gitam/anaconda3/envs/meta/bin/metaphlan_databases/mpa_v295_CHOCOPhlAn_201901
#/oak/stanford/groups/quake/gita/raw/env/meta/bin/metaphlan_databases/mpa_v295_CHOCOPhlAn_201901

#rule merge_metaphlan_tables
name_merge: merge
mem_merge: 16000
threads_merge: 4

#rule metaphlan_tables_species
name_species: species
mem_species: 16000
threads_species: 4

#rule hclust
name_hclust: hclust
mem_hclust: 16000
threads_hclust: 4

#rule export2graphlan
name_export: export
mem_export: 16000
threads_export: 4

#rule graphlan
name_graphlan: graphlan
mem_graphlan: 16000
threads_graphlan: 4

#rule relabel
name_relabel: relabel
mem_relabel: 16000
threads_relabel: 4

#rule merge_relabeled_reads
name_merge_relabeled: join
mem_merge_relabeled: 16000
threads_merge_relabeled: 4

#rule OTUs_fromAllreads
name_OTUsFromAllReads: OTUs_fromAllreads
mem_OTUsFromAllReads: 64000
threads_OTUsFromAllReads: 12
otu_percent_id_threshold: 0.90

#rule OTU_table
name_OTU_table: OTU_table
mem_OTU_table: 16000
threads_OTU_table: 4

#rule OTU_table_rare
name_OTU_table_rare: OTU_table_rare
mem_OTU_table_rare: 16000
threads_OTU_table_rare: 4
rare: 500 #number of reads to sub-sample from each sample

